<?php
	$admin = $this->admin->getData(); 
?>
<header class="topbar">
	<nav class="navbar top-navbar navbar-expand-md navbar-light">
		<div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->url->getBaseUri()?>">
                <span><?php echo \Phalcon\Tag::image(array("/img/logo.png",'alt'=>'Demo','class' => "light-logo"));?></span>
             </a>
        </div>
        <div class="navbar-collapse">
        	<ul class="navbar-nav mr-auto mt-md-0"></ul>
	        <ul class="navbar-nav my-lg-0">
	        	<li class="nav-item dropdown">
	        		<?php echo $this->tag->form(array("/admin/logout", "method" => "post")); ?>
                    <?php echo $this->tag->submitButton(array('Logout', 'class' => 'btn btn-danger btn-rounded')); ?>
                    <?php echo $this->tag->endForm(); ?>
	            </li>
	        </ul>
	    </div>
	</nav>
</header>